version: '3.8'

services:
  whisper-api:
    build: .
    container_name: faster-whisper-api
    environment:
      - OMP_NUM_THREADS=4
    volumes:
      - ./temp:/tmp/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 